---
- name: install required packages
  apt:
    pkg:
      - curl
      - git
      - lynx
      - python3-pip
      - apt-transport-https
    state: latest
    update_cache: true

- name: add docker apt Key
  apt_key:
    url: "{{ docker_apt_key }}"
    state: present

- name: add docker repository
  apt_repository:
    repo: "{{ docker_apt_repository }}"
    state: present

- name: install docker package
  apt:
    name: "{{ docker_package }}"
    state: latest
    update_cache: true
