---
- hosts: app
  become: true
  tasks:
  
  - name: Install required system packages
    apt:
      pkg:
        - curl
        - git
        - lynx
        - python3-pip
      state: latest
      update_cache: true

  - name: Install Docker SDK for Python
    pip:
      name: docker
      state: present
      executable: pip3

  - name: Add Docker GPG apt Key
    apt_key:
      url: "{{ docker_apt_key_url }}"
      state: present

  - name: Add Docker Repository
    apt_repository:
      repo: "{{ docker_apt_repository }}"
      state: present

  - name: Update apt and install docker-ce
    apt:
      name: "{{ docker_package }}"
      state: latest
      update_cache: true

